### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'name'

### ISSUE THREAD

**Issue by AzureIP** [gabrieldemarmiesse/heatmaps#10]
Hi,

I tried your code but it didn't worked:

`Model type detected: local pooling - flatten
Traceback (most recent call last):
  File "D:/Uni/Neuro/AttemptTwo/code/display_a_heatmap.py", line 45, in <module>
    new_model = to_heatmap(my_custom_model)
  File "d:\uni\neuro\attempttwo\venv\heatmaps-master\heatmaps-master\heatmap\heatmap.py", line 233, in to_heatmap
    middle_model = Model(inputs=model.layers[1].input, outputs=model.layers[index - 1].output)
  File "D:\Uni\Neuro\AttemptTwo\venv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Uni\Neuro\AttemptTwo\venv\lib\site-packages\keras\engine\network.py", line 91, in __init__
    self._init_graph_network(*args, **kwargs)
  File "D:\Uni\Neuro\AttemptTwo\venv\lib\site-packages\keras\engine\network.py", line 183, in _init_graph_network
    'The tensor that caused the issue was: ' +
AttributeError: 'Model' object has no attribute 'name'`

my code
`import matplotlib.pyplot as plt
import numpy as np
from keras.applications.imagenet_utils import preprocess_input
from keras.models import load_model
from keras.preprocessing import image
from keras import backend as K

from heatmap import to_heatmap, synset_to_dfs_ids

def display_heatmap(new_model, img_path, ids, preprocessing=None):
    # The quality is reduced.
    # If you have more than 8GB of RAM, you can try to increase it.
    img = image.load_img(img_path, target_size=(277, 277))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    if preprocessing is not None:
        x = preprocess_input(x)

    out = new_model.predict(x)

    heatmap = out[0]  # Removing batch axis.

    if K.image_data_format() == 'channels_first':
        heatmap = heatmap[ids]
        if heatmap.ndim == 3:
            heatmap = np.sum(heatmap, axis=0)
    else:
        heatmap = heatmap[:, :, ids]
        if heatmap.ndim == 3:
            heatmap = np.sum(heatmap, axis=2)

    plt.imshow(heatmap, interpolation="none")
    plt.show()

# model = VGG16()
# new_model = to_heatmap(model)
#
# s = "n02084071"  # Imagenet code for "dog"
# ids = synset_to_dfs_ids(s)
# display_heatmap(new_model, "./dog.jpg", ids, preprocess_input)

my_custom_model = load_model('saved_instance.hdf5')
new_model = to_heatmap(my_custom_model)
idx = 0  # The index of the class you care about, here the first one.
display_heatmap(new_model, "./input images/_MG_2881.jpg", idx)`

my model
`def create_model():

    model = Sequential()
    model.add(Convolution2D(96, 11, 11,
                            border_mode='valid', subsample=(4, 4),
                            input_shape=(image_size, image_size, 3) ) )
    model.add(Activation('relu'))
    model.add(MaxPooling2D((3, 3), strides=(2, 2)))

    model.add(Convolution2D(128, 5, 5, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D((3, 3), strides=(2, 2)))

    model.add(Convolution2D(150, 3, 3, border_mode='valid'))
    model.add(Activation('relu'))

    model.add(Flatten())
    model.add(Dense(2048))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))

    model.add(Dense(1024))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))

    model.add(Dense(2))
    model.add(Activation('linear'))

    model.compile(loss='mean_squared_error', optimizer=Adadelta())
    return model`

**Comment by gabrieldemarmiesse** [comment]
Thanks for the detailed report! I'll look into it this weekend.

**Comment by gabrieldemarmiesse** [comment]
Just as a quick thing you can try, can you use the functional API instead of the sequential one? I think my code doesn't handle the sequential API yet.

**Comment by hija** [comment]
Just as a little addition: To convert a sequential model to a functional API model, you can just use

``functional_model = seqmodel.model``

if you have used the ``.compile(...)`` or ``.build()`` function on your model before. So you do not need to rewrite your whole code, but you just need to add one line.

**Comment by gabrieldemarmiesse** [comment]
I didn't know it was possible. I'll add the automatic conversion in my
script. Thanks for the info!

**Comment by gabrieldemarmiesse** [comment]
I've implemented the conversion. Now sequential models should work. Can you try? Thank you.
