### ISSUE TITLE
can it be used to grey-level imageset network?

### ISSUE THREAD

**Issue by mahaoyanghb** [gabrieldemarmiesse/heatmaps#13]
**my network is designed for grey level pictures, so there is only 1 channel.
I tried to apply this lib to my model, at first, it report channel not match, and I find the code , changed channel num to 1 ,** 

if K.image_data_format() == 'channels_first':
        img_input = Input(shape=(1, None, None))
    else:
        img_input = Input(shape=(None, None, 1))

**run it again, now  it report another problem:
I can't understand, could you please help ?**

Traceback (most recent call last):
  File "seam_heatmap.py", line 93, in <module>
    new_model = to_heatmap(model)
  File "D:\DeepLearning\Python3.5.2\lib\site-packages\heatmaps\heatmap\heatmap.py", line 258, in to_heatmap
    x = add_reshaped_layer(model.layers[index + 2], x, size, atrous_rate=atrous_rate)
  File "D:\DeepLearning\Python3.5.2\lib\site-packages\heatmaps\heatmap\heatmap.py", line 211, in add_reshaped_layer
    insert_weights(layer, new_layer)
  File "D:\DeepLearning\Python3.5.2\lib\site-packages\heatmaps\heatmap\heatmap.py", line 156, in insert_weights
    new_W = W.reshape((ax1, ax2, previous_filter, n_filter))
ValueError: cannot reshape array of size 184320 into shape (4,4,64,120)

**Comment by mahaoyanghb** [comment]
solved
after analyze the code carefully, I found reason , the last conv layer 's feature map is not square  in my network, 6*4 resolution, and function add_reshaped_layer just consider square feature map, so shape not match.
changed function below, it works:

def add_reshaped_layer(layer, x, size_r,size_c, no_activation=False, atrous_rate=None):
    conf = layer.get_config()

    if no_activation:
        activation = "linear"
    else:
        activation = conf["activation"]

    print(layer.name+',activation:'+str(activation))
    if size_r == 1 and size_c == 1:
        new_layer = Conv2D(conf["units"], (1, 1),
                           activation=activation, name=conf['name'])
    else:
        new_layer = Conv2D(conf["units"], (size_r, size_c),
                           dilation_rate=(atrous_rate, atrous_rate),
                           activation=activation, padding='valid',
                           name=conf['name'])

    x = new_layer(x)
    # We transfer the weights:
    insert_weights(layer, new_layer)
    return x


and change the parameter in calling where called this function.

**Comment by mahaoyanghb** [comment]
solved
after analyze the code carefully, I found reason , the last conv layer 's feature map is not square in my network, 6*4 resolution, and function add_reshaped_layer just consider square feature map, so shape not match.
changed function below, it works:

def add_reshaped_layer(layer, x, size_r,size_c, no_activation=False, atrous_rate=None):
conf = layer.get_config()

if no_activation:
    activation = "linear"
else:
    activation = conf["activation"]

print(layer.name+',activation:'+str(activation))
if size_r == 1 and size_c == 1:
    new_layer = Conv2D(conf["units"], (1, 1),
                       activation=activation, name=conf['name'])
else:
    new_layer = Conv2D(conf["units"], (size_r, size_c),
                       dilation_rate=(atrous_rate, atrous_rate),
                       activation=activation, padding='valid',
                       name=conf['name'])

x = new_layer(x)
# We transfer the weights:
insert_weights(layer, new_layer)
return x

**Comment by mahaoyanghb** [comment]
solved
after analyze the code carefully, I found reason , the last conv layer 's feature map is not square in my network, 6*4 resolution, and function add_reshaped_layer just consider square feature map, so shape not match.
changed function below, it works:

def add_reshaped_layer(layer, x, size_r,size_c, no_activation=False, atrous_rate=None):
conf = layer.get_config()

if no_activation:
    activation = "linear"
else:
    activation = conf["activation"]

print(layer.name+',activation:'+str(activation))
if size_r == 1 and size_c == 1:
    new_layer = Conv2D(conf["units"], (1, 1),
                       activation=activation, name=conf['name'])
else:
    new_layer = Conv2D(conf["units"], (size_r, size_c),
                       dilation_rate=(atrous_rate, atrous_rate),
                       activation=activation, padding='valid',
                       name=conf['name'])

x = new_layer(x)
# We transfer the weights:
insert_weights(layer, new_layer)
return x
