### ISSUE TITLE
MemoryError on Raspberry Pi

### ISSUE THREAD

**Issue by abdualhag** [gabrieldemarmiesse/heatmaps#7]
Hi, so I was playing around with raspberry pi and tried using Keras to see how it handle which by the was not so well but it worked. When I tried to run the heatmap demo however, I always get a memory error even after reducing the size of the output image which is probably not what causes the crash to start with. I looked it up on-line and the solution seem to related to batch size, something which you would be able to refer me to where in the package I might find. The error I receive is found bellow, the same error appears with python2:

```
pi@raspberrypi:~/heatmaps/examples $ python3 demo.py 
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
Traceback (most recent call last):
  File "demo.py", line 38, in <module>
    model = VGG16()
  File "/home/pi/.local/lib/python3.5/site-packages/keras/applications/vgg16.py", line 146, in VGG16
    x = Dense(4096, activation='relu', name='fc1')(x)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 590, in __call__
    self.build(input_shapes[0])
  File "/home/pi/.local/lib/python3.5/site-packages/keras/layers/core.py", line 842, in build
    constraint=self.kernel_constraint)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 414, in add_weight
    constraint=constraint)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 154, in variable
    strict=False)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/sharedvalue.py", line 268, in shared
    allow_downcast=allow_downcast, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/theano/tensor/sharedvar.py", line 54, in tensor_constructor
    value=np.array(value, copy=(not borrow)),
MemoryError: you might consider using 'theano.shared(..., borrow=True)'

```
**Update:**

The issue is exclusive to vgg16, any call to vgg16  by any code causes the problem. I will close the issue after your reply as it does not seem to be an issue related to your package.

I do however have an issue as things work fine vgg16 but not much so with ResNet50 as I always receive the following error even on my usual machine.
```

Using Theano backend.
Model type detected: local pooling - flatten
Model cut at layer: 173
Pool size infered: 1
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    new_model = to_heatmap(model)
  File "/home/pi/heatmaps/heatmap/heatmap.py", line 259, in to_heatmap
    x = copy_last_layers(model, index + 3, x)
  File "/home/pi/heatmaps/heatmap/heatmap.py", line 182, in copy_last_layers
    if last_activation == 'softmax':
UnboundLocalError: local variable 'last_activation' referenced before assignment

```

It also does not work with InceptionV3 as it yield the following error.

```
Using Theano backend.
Model type detected: global pooling
Model cut at layer: 310
Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    new_model = to_heatmap(model)
  File "/home/abdu/anaconda2/envs/theano/heatmaps/heatmap/heatmap.py", line 239, in to_heatmap
    x = copy_last_layers(model, index + 1, x)
  File "/home/abdu/anaconda2/envs/theano/heatmaps/heatmap/heatmap.py", line 169, in copy_last_layers
    x = add_reshaped_layer(layer, x, 1, no_activation=True)
  File "/home/abdu/anaconda2/envs/theano/heatmaps/heatmap/heatmap.py", line 209, in add_reshaped_layer
    x = new_layer(x)
  File "/home/abdu/anaconda2/envs/theano/lib/python2.7/site-packages/keras/engine/topology.py", line 573, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/abdu/anaconda2/envs/theano/lib/python2.7/site-packages/keras/engine/topology.py", line 472, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer predictions: expected ndim=4, found ndim=2

```
Using DenseNet121 and Theano:
```

Using Theano backend.
Model type detected: global pooling
Model cut at layer: 425
Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    new_model = to_heatmap(model)
  File "/home/abdu/anaconda2/envs/theano/heatmaps/heatmap/heatmap.py", line 239, in to_heatmap
    x = copy_last_layers(model, index + 1, x)
  File "/home/abdu/anaconda2/envs/theano/heatmaps/heatmap/heatmap.py", line 169, in copy_last_layers
    x = add_reshaped_layer(layer, x, 1, no_activation=True)
  File "/home/abdu/anaconda2/envs/theano/heatmaps/heatmap/heatmap.py", line 209, in add_reshaped_layer
    x = new_layer(x)
  File "/home/abdu/anaconda2/envs/theano/lib/python2.7/site-packages/keras/engine/topology.py", line 573, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/abdu/anaconda2/envs/theano/lib/python2.7/site-packages/keras/engine/topology.py", line 472, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer fc1000: expected ndim=4, found ndim=2

```

**Another Update:**

So I test some other models using TesorFlow backend and I basically recive the same error which as follow, note that vgg16 model run with no issue.
```

Model type detected: global pooling
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    new_model = to_heatmap(model)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/heatmaps/heatmap/heatmap.py", line 234, in to_heatmap
    x = middle_model(img_input)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 2078, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 2229, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/layers/normalization.py", line 185, in call
    self.momentum),
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 180, in _zero_debias
    "biased", initializer=biased_initializer, trainable=False)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable block1_conv1_bn/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/layers/normalization.py", line 185, in call
    self.momentum),
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)

```
I would not wanna bother you with all these models but it would be great i I could at least get it to work with either MobileNet or DenseNet121 as they are light models which is what I need for Raspberry Pi. You should also note how errors are different based on the backend I am using, same error using TensorFlow while different errors based on the model used with Theano.
 
Thanks

**Comment by gabrieldemarmiesse** [comment]
Hi! 
Thanks for reporting me all this! The memory error isn't surprising as the vgg16 is around 400MB already but models like onception are more around 100MB. I will look at the other models you mentioned  this weekend and see why it didn't work out.

**Comment by abdualhag** [comment]
Looking forward to hear back from  you.

**Comment by gabrieldemarmiesse** [comment]
Hi!
I just pushed a fix for the resnet. I tested it with tensorflow but it should also work with Theano. I'm going to look into the other networks. Please keep me updated if you find any issue.

**Comment by gabrieldemarmiesse** [comment]
I pushed the fix for densenet and inception. Mobilenet isn't working yet.

**Comment by abdualhag** [comment]
Hi!
Thanks you so much. I just reinstalled the package and ResNet50 worked well with Theano. This however was not the case with Tensorflow as I receive the following error:
```

Model type detected: local pooling - flatten
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    new_model = to_heatmap(model)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/heatmaps/heatmap/heatmap.py", line 234, in to_heatmap
    x = middle_model(img_input)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 2078, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 2229, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/layers/normalization.py", line 185, in call
    self.momentum),
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 180, in _zero_debias
    "biased", initializer=biased_initializer, trainable=False)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable bn_conv1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/layers/normalization.py", line 185, in call
    self.momentum),
  File "/home/abdu/anaconda2/envs/tensorflowGpu/lib/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)

```


You should know that I am using tensorflow gpu. I will go a head and test the rest. 
Thanks

**Comment by gabrieldemarmiesse** [comment]
Thanks for that. You can run the `tests/test.py` to check what is working on your end and what is not. I use tensorflow cpu for testing but I don't think it has any influence. Anyway, I don't think I can fix a bug that I can't reproduce sadly. Keep me updated. Maybe I'll understand how to fix it.

**Comment by abdualhag** [comment]
Okay. I just finished testing denenet and inception using theano backend and they both work poorly on demo.py with the dog class. See comparison below:

ResNet50
![resnet50](https://user-images.githubusercontent.com/25646205/36938084-6969eefa-1eea-11e8-95be-f0b82b7cd842.png)

DenseNet121

![desnet121](https://user-images.githubusercontent.com/25646205/36938088-73fffc88-1eea-11e8-8a2b-c3f469fed2d4.png)

InceptionV3
![inceptionv3](https://user-images.githubusercontent.com/25646205/36938091-84bf670c-1eea-11e8-8747-34e105b487d4.png)

This is worrying because the class is definitely being recognized as a dog. Here is the output from DenseNet

```
 Using Theano backend.
('Predicted:', [(u'n02113023', u'Pembroke', 0.51888126), (u'n02109961', u'Eskimo_dog', 0.18552731), (u'n02110185', u'Siberian_husky', 0.12073633)])
```

I will test tensorflow and let you know how it ended.

**Comment by gabrieldemarmiesse** [comment]
I just had this error, you need to change the preprocessing.

**Comment by gabrieldemarmiesse** [comment]
For example, if you want to try with inception resnet, you need to change the preprocessing like this:

```python
import matplotlib.pyplot as plt
import numpy as np
from keras.applications.inception_resnet_v2 import preprocess_input
from keras.applications import *
from keras.preprocessing import image
from keras import backend as K

from heatmap import synset_to_dfs_ids
from heatmap import to_heatmap


def display_heatmap(new_model, img_path, ids, preprocessing=None):
    # The quality is reduced.
    # If you have more than 8GB of RAM, you can try to increase it.
    img = image.load_img(img_path, target_size=(800, 1280))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    if preprocessing is not None:
        x = preprocess_input(x)

    out = new_model.predict(x)

    heatmap = out[0]  # Removing batch axis.

    if K.image_data_format() == 'channels_first':
        heatmap = heatmap[ids]
        if heatmap.ndim == 3:
            heatmap = np.sum(heatmap, axis=0)
    else:
        heatmap = heatmap[:, :, ids]
        if heatmap.ndim == 3:
            heatmap = np.sum(heatmap, axis=2)

    plt.imshow(heatmap, interpolation="none")
    plt.show()


model = InceptionResNetV2()
new_model = to_heatmap(model)

s = "n02084071"  # Imagenet code for "dog"
ids = synset_to_dfs_ids(s)
display_heatmap(new_model, "./dog.jpg", ids, preprocess_input)
```

**Comment by abdualhag** [comment]
In regard to tensorflow, all except VGG16 broke down with the same error as before. My guess is that my environment in a weird state. I will test a different environment and see if things changes. Really surprise that classifying work however.

**Comment by gabrieldemarmiesse** [comment]
I just pushed the fix for mobilenets. All was tested under tensorflow cpu - python 3.6. But since keras is very good at hiding the backends, I'm pretty sure it should work for Theano and tensorflow-gpu too.

**Comment by gabrieldemarmiesse** [comment]
Indeed it's possible that there is there is a problem in your environnement. Maybe update tensorflow? It's just a wild guess.

**Comment by gabrieldemarmiesse** [comment]
can you give me the output of a `pip freeze`?

**Comment by abdualhag** [comment]
First thing first, I really appreciate your help. Just finished testing all models on tensorflow cpu environment and everything worked well. Also, changing the preprocessing fixed the issue of the poor heatmap. As for the tensorflow gpu environment, below is the output of pip freeze:

```
(tensorflowGpu) abdu@abdu-Default-string:~/anaconda2/envs/tensorflowGpu$ pip freeze
attrs==17.4.0
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.ssl-match-hostname==3.5.0.1
backports.weakref==1.0rc1
bleach==1.5.0
certifi==2016.2.28
cycler==0.10.0
funcsigs==1.0.2
functools32==3.2.3.post2
h5py==2.7.1
html5lib==0.9999999
Keras==2.1.3
-e git+https://github.com/gabrieldemarmiesse/heatmaps.git@415b6cc19d8d71aaf647bb3a36b903f4f6bbda06#egg=Keras_to_heatmaps
Markdown==2.2.0
matplotlib==2.1.1
mock==2.0.0
numpy==1.14.0
pbr==3.1.1
Pillow==5.0.0
pluggy==0.6.0
protobuf==3.5.1
py==1.5.2
pycairo==1.10.0
pyparsing==2.2.0
pytest==3.4.1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
scipy==1.0.0
singledispatch==3.4.0.3
six==1.11.0
subprocess32==3.2.7
tensorflow-gpu==1.2.0
tornado==4.5.3
Werkzeug==0.14.1

```

I will try to reinstall tensorflow gpu and let you know how did it go.

**Comment by gabrieldemarmiesse** [comment]
Tensorflow is right now at version 1.6. Yours is at 1.2. Maybe this is the issue.

**Comment by abdualhag** [comment]
That is probably why. This will take forever to fix as I need to update all dependency. I will let you know how it turned out when I fix everything. Thanks for the help.

**Comment by gabrieldemarmiesse** [comment]
I'm glad to help, and thanks for reporting the bugs!
